"""empty message

Revision ID: 466c32468e1a
Revises: 7f50c64827a1
Create Date: 2018-01-16 09:45:40.474237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466c32468e1a'
down_revision = '7f50c64827a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_description', sa.String(length=255), nullable=True))
    op.add_column('recipes', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('recipe_description', sa.Text(), nullable=True))
    op.drop_column('recipes', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('recipes', 'recipe_description')
    op.drop_column('recipes', 'instructions')
    op.drop_column('categories', 'category_description')
    # ### end Alembic commands ###
