"""empty message

Revision ID: 54e0fcb02bf1
Revises: 8069c5bb3b41
Create Date: 2017-12-15 11:39:35.967000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e0fcb02bf1'
down_revision = '8069c5bb3b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('recipename', sa.String(length=256), nullable=True))
    op.drop_constraint(u'recipes_title_key', 'recipes', type_='unique')
    op.create_unique_constraint(None, 'recipes', ['recipename'])
    op.drop_column('recipes', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipes', type_='unique')
    op.create_unique_constraint(u'recipes_title_key', 'recipes', ['title'])
    op.drop_column('recipes', 'recipename')
    # ### end Alembic commands ###
