"""empty message

Revision ID: 60cde4081cdd
Revises: 3fcc49650bf2
Create Date: 2017-12-18 14:45:01.422000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60cde4081cdd'
down_revision = '3fcc49650bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'recipes_recipename_key', 'recipes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'recipes_recipename_key', 'recipes', ['recipename'])
    # ### end Alembic commands ###
