"""empty message

Revision ID: fcbe767d810d
Revises: 66c00aa3be6e
Create Date: 2018-01-08 12:06:27.685499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcbe767d810d'
down_revision = '66c00aa3be6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_answer', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_answer')
    # ### end Alembic commands ###
